CREATE TABLE demo.address
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street       VARCHAR(255)                            NOT NULL,
    house_number VARCHAR(255)                            NOT NULL,
    postal_code  VARCHAR(5)                              NOT NULL,
    city         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);