# docker-compose.yml
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: generic-spring-demo
      POSTGRES_PASSWORD: generic-spring-demo
      POSTGRES_DB: generic-spring-demo
    volumes:
      - ./data:/var/lib/postgresql/data
