### Get all addresses
GET http://localhost:8080/api/addresses
Accept: application/json

###

### Get address by ID
GET http://localhost:8080/api/addresses/1
Accept: application/json

###

### Create a new address (1/4)
POST http://localhost:8080/api/addresses
Content-Type: application/json

{
  "street": "Main Street",
  "houseNumber": "123",
  "postalCode": "12345",
  "city": "SomeCity"
}

###

### Create a new address (2/4)
POST http://localhost:8080/api/addresses
Content-Type: application/json

{
  "street": "Second Street",
  "houseNumber": "456",
  "postalCode": "67890",
  "city": "AnotherCity"
}

###

### Create a new address (3/4)
POST http://localhost:8080/api/addresses
Content-Type: application/json

{
  "street": "Third Avenue",
  "houseNumber": "789",
  "postalCode": "10112",
  "city": "YetAnotherCity"
}

###

### Create a new address (4/4)
POST http://localhost:8080/api/addresses
Content-Type: application/json

{
  "street": "Fourth Blvd",
  "houseNumber": "101",
  "postalCode": "31415",
  "city": "FinalCity"
}

###

### Update an address by ID
PUT http://localhost:8080/api/addresses/1
Content-Type: application/json

{
  "street": "Main Street Updated",
  "houseNumber": "124",
  "postalCode": "54321",
  "city": "SomeCity Updated"
}

###

### Delete an address by ID
DELETE http://localhost:8080/api/addresses/1